# Python 4 Data Science Excercise


## Exercise 1
Set up your Jupyter Notebook. Either by hand or by Anaconda. 

## Exercise 2
Read the first 25 Exercises from [101 NumPy Exercises](https://www.machinelearningplus.com/python/101-numpy-exercises-python/).


In [54]:
print("Here are the first 25 exercies from 101 NumPy Exercises:")

Here are the first 25 exercies from 101 NumPy Exercises:


1: Import numpy as np and see the version

In [1]:
import numpy as np
print(np.__version__)


1.21.5


2:  Create a 1D array of numbers from 0 to 9

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3: Create a 3×3 numpy array of all True’s

In [3]:
np.full((3, 3), True, dtype=bool)


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

4: Extract all odd numbers from an array

In [9]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
odd_arr = arr[arr % 2 == 1]
odd_arr

array([1, 3, 5, 7, 9])

5: Replace all odd numbers in arr with -1

In [7]:
arr = np.arange(10)
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

6: Replace all odd numbers in arr with -1 without changing arr

In [10]:
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

7: Convert a 1D array to a 2D array with 2 rows

In [14]:
arr = np.arange(10)
arr.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

8: Stack arrays a and b vertically

In [20]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.vstack([a, b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

9: Stack the arrays a and b horizontally.

In [21]:
a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

10: Create the pattern `1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3` without hardcoding. Use only numpy functions and the below input array a.

In [22]:
a = np.array([1,2,3])
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

11: Get the common items between a and b

In [23]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)


array([2, 4])

12: From array a remove all items present in array b

In [24]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

13: Get the positions where elements of a and b match

In [25]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)


(array([1, 3, 5, 7]),)

 14: Get all items between 5 and 10 from a.

In [26]:
a = np.arange(15)
a[(a >= 5) & (a <= 10)]


array([ 5,  6,  7,  8,  9, 10])

15: Convert the function maxx that works on two scalars, to work on two arrays.

In [28]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

16: Swap columns 1 and 2 in the array arr.

In [30]:
arr = np.arange(9).reshape(3,3)
arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

17: Swap rows 1 and 2 in the array arr

In [31]:
# Input
arr = np.arange(9).reshape(3,3)
# Solution
arr[[1,0,2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

18: Reverse the rows of a 2D array arr.

In [32]:
# Input
arr = np.arange(9).reshape(3,3)
# Solution
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

19: Reverse the columns of a 2D array arr.

In [33]:
# Input
arr = np.arange(9).reshape(3,3)
# Solution
arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

20: Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

In [34]:
# Input
arr = np.arange(9).reshape(3,3)

# Solution
rand_arr = np.random.uniform(5,10, size=(5,3))
print(rand_arr)

[[6.02160496 9.13317544 6.54736363]
 [7.78993492 6.00023387 9.05711512]
 [6.58658981 7.14189788 5.69679595]
 [9.5771128  6.27202137 8.7865779 ]
 [6.66146818 8.32075482 5.55661785]]


21: Print or show only 3 decimal places of the numpy array rand_arr

In [39]:
# Input
rand_arr = np.random.random([5,3])

# Limit to 3 decimal places
np.set_printoptions(precision=3)
rand_arr[:4]

array([[0.351, 0.27 , 0.538],
       [0.301, 0.344, 0.624],
       [0.397, 0.046, 0.758],
       [0.621, 0.71 , 0.638]])

22: Pretty print rand_arr by suppressing the scientific notation (like 1e10)

In [41]:
# Reset printoptions to default
np.set_printoptions(suppress=False)

# Set new printoptions
np.set_printoptions(suppress=True, precision=6)  # precision is optional

# Create the random array
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

23: Limit the number of items printed in python numpy array a to a maximum of 6 elements.

In [43]:
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

24: Print the full numpy array a without truncating.

In [52]:
import sys

# Input
np.set_printoptions(threshold=6)
a = np.arange(15)

# Solution
np.set_printoptions(threshold=sys.maxsize)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

25: Import the iris dataset keeping the text intact.

In [53]:
# Solution
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Print the first 3 rows
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

## Exercise 3
Do the following exercise in a Jupyter Notebook:

1. Load the countries.csv directly via URL import into your panda data frame!